server:
  port: 8080
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:BdEwu2023@localhost:8082/eureka/

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile, user.read
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/spring
        provider:
          spring:
            issuer-uri: http://localhost:8083

  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      password: redis?pass
      username: default

  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - SaveSession
      discovery:
        locator:
          enabled: true
      globalcors:
        add-to-simple-url-handler-mapping: true
      routes:

        - id: authorization-server
          uri: http://localhost:8083
          predicates:
            - Path=/authorization/**
          filters:
            - RewritePath=/authorization/(?<path>.*), /$\{path}

        - id: user-service
          uri: http://localhost:8090
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}

        - id: utility-service
          uri: http://localhost:8091
          predicates:
            - Path=/utility/**
          filters:
            - RewritePath=/utility/(?<path>.*), /$\{path}
